version: '2'
services:

    server:
        image: app_review_server
        build:
            context: ./
            dockerfile: server/Dockerfile
        ports:
            - "127.0.0.1:8000:8000"
        entrypoint: ["python3", "/code/manage.py", "runserver", "0.0.0.0:8000"]

    client:
        image: app_review_client
        build:
            context: ./
            dockerfile: client/Dockerfile
        ports:
            - "127.0.0.1:80:80"
        entrypoint: ["nginx", "-g", "daemon off;"]
